DROP TABLE IF EXISTS SETTINGS CASCADE;

CREATE FUNCTION SYSTEM_USER_NAME() RETURNS VARCHAR(10)
LANGUAGE JAVA DETERMINISTIC NO SQL
EXTERNAL NAME 'CLASSPATH:de.freese.pim.core.utils.Utils.getSystemUserName'
;

--DEFAULT SYSTEM_USER_NAME()
CREATE TABLE SETTINGS
(
   USER_ID	VARCHAR (50) NOT NULL,
   KEY		VARCHAR (50) NOT NULL,
   VALUE	VARCHAR (50)
);
--ALTER TABLE SETTINGS ADD CONSTRAINT SETTINGS_PK PRIMARY KEY (ID);
CREATE UNIQUE INDEX SETTINGS_UNQ ON SETTINGS (USER_ID, KEY, VALUE);
ALTER TABLE SETTINGS ADD CONSTRAINT SETTINGS_CK_USER CHECK(LENGTH(TRIM(USER_ID)) > 0);
ALTER TABLE SETTINGS ADD CONSTRAINT SETTINGS_CK_KEY CHECK(LENGTH(TRIM(KEY)) > 0);
COMMENT ON TABLE SETTINGS IS 'Tabelle für die User-Spezifische Konfiguration';
COMMENT ON COLUMN SETTINGS.USER_ID IS 'Eigentümer';
COMMENT ON COLUMN SETTINGS.KEY IS 'Schlüssel eines Attributes';
COMMENT ON COLUMN SETTINGS.VALUE IS 'Wert eines Attributes';
