DROP VIEW IF EXISTS V_ADDRESSBOOK CASCADE;
DROP TABLE IF EXISTS KONTAKT_ATTRIBUT CASCADE;
DROP TABLE IF EXISTS KONTAKT CASCADE;
DROP SEQUENCE IF EXISTS KONTAKT_SEQ;

CREATE SEQUENCE KONTAKT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE KONTAKT
(
    ID          BIGINT NOT NULL,
	USER_ID		VARCHAR (50) NOT NULL,
	NACHNAME	VARCHAR (50) NOT NULL,
	VORNAME		VARCHAR (50)
);
ALTER TABLE KONTAKT ADD CONSTRAINT KONTAKT_PK PRIMARY KEY (ID);
CREATE INDEX KONTAKT_IDX_ID ON KONTAKT (ID);
CREATE INDEX KONTAKT_IDX_USERID ON KONTAKT (USER_ID);
CREATE UNIQUE INDEX KONTAKT_UNQ ON KONTAKT (USER_ID, NACHNAME, VORNAME);
ALTER TABLE KONTAKT ADD CONSTRAINT KONTAKT_CK_NACHNAME CHECK(LENGTH(TRIM(NACHNAME)) > 0);
ALTER TABLE KONTAKT ADD CONSTRAINT KONTAKT_CK_VORNAME CHECK(VORNAME IS NULL OR LENGTH(TRIM(VORNAME)) > 0);
COMMENT ON TABLE KONTAKT IS 'Tabelle für eindeutige Kontakte (Vorname, Nachname)';
COMMENT ON COLUMN KONTAKT.USER_ID IS 'Eigentümer';
COMMENT ON COLUMN KONTAKT.ID IS 'Primary Key';
COMMENT ON COLUMN KONTAKT.NACHNAME IS 'Der Nachname es Kontakts';
COMMENT ON COLUMN KONTAKT.VORNAME IS 'Der Vorname es Kontakts';

CREATE TABLE KONTAKT_ATTRIBUT
(
	KONTAKT_ID	BIGINT NOT NULL,
	ATTRIBUT	VARCHAR (20) NOT NULL,
	WERT		VARCHAR (1000) NOT NULL
);
ALTER TABLE KONTAKT_ATTRIBUT ADD CONSTRAINT KONTAKTATTRIBUT_FK FOREIGN KEY (KONTAKT_ID) REFERENCES KONTAKT (ID);
CREATE INDEX KONTAKTATTRIBUT_IDX_KONTAKTID ON KONTAKT_ATTRIBUT (KONTAKT_ID);
CREATE UNIQUE INDEX KONTAKTATTRIBUT_UNQ ON KONTAKT_ATTRIBUT (KONTAKT_ID, ATTRIBUT);
ALTER TABLE KONTAKT_ATTRIBUT ADD CONSTRAINT KONTAKTATTRIBUT_CK_ATTRIBUT CHECK(LENGTH(TRIM(ATTRIBUT)) > 0);
ALTER TABLE KONTAKT_ATTRIBUT ADD CONSTRAINT KONTAKTATTRIBUT_CK_WERT CHECK(LENGTH(TRIM(WERT)) > 0);
COMMENT ON TABLE KONTAKT_ATTRIBUT IS 'Tabelle für Key-Value Attribute eines Kontakts';
COMMENT ON COLUMN KONTAKT_ATTRIBUT.KONTAKT_ID IS 'Foreign Key des Kontakts';
COMMENT ON COLUMN KONTAKT_ATTRIBUT.ATTRIBUT IS 'Name des Attributs (BIRTHDAY, STREET, ...)';
COMMENT ON COLUMN KONTAKT_ATTRIBUT.WERT IS 'Wert des Attributs (BIRTHDAY, STREET, ...)';

CREATE VIEW V_ADDRESSBOOK AS
SELECT k.USER_ID, k.ID, k.NACHNAME, k.VORNAME, ka.ATTRIBUT, ka.WERT
    FROM KONTAKT k LEFT OUTER JOIN KONTAKT_ATTRIBUT ka ON ka.KONTAKT_ID = k.ID
ORDER BY k.NACHNAME ASC;
